--- Makefile.orig	2005-05-24 12:29:56.000000000 +0300
+++ Makefile	2011-11-24 14:47:14.023000008 +0200
@@ -36,7 +36,7 @@
 LD=g++
 CC=gcc
 CXXFLAGS=-Wall -pedantic -O2 `fltk-config --cxxflags`
-LDFLAGS=`fltk-config --use-images --ldflags` -lasound -lm -lpthread
+LDFLAGS=`fltk-config --use-images --ldflags` -lasound -lm -lpthread -ljpeg
 CFLAGS=-O2
 
 .PHONY: help all targz bz2 dist clean
